server:
  port: 9090
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/im?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #redis配置
  redis:
    host: 124.222.37.177
    password: wxy19981207
    port: 8000
##集群配置
#    cluster:
#      nodes:
  #邮箱配置
  mail:
    host: smtp.126.com #发送邮件服务器
    username: wxy888_8@126.com #发送邮件的邮箱地址
    password: FVDJEUAWYGSYUHRF #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: wxy888_8@126.com # 发送邮件的地址，和上面username一致
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
#阿里云OSS配置
#aliyun:
#  oss:
#    endpoint: oss-cn-nanjing.aliyuncs.com
#    access-key-id:
#    access-key-secret:
#    bucketname:

# MyBatis 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

